export enum EnoWords {
  ADD = '+',
  SUBTRACT = '-',
  MULTIPLY = '*',
  DIVIDE = '/',
  POP = 'pop',
  DUP = 'dup',
  SWAP = 'swap',
  EQUALS = '==',
  IF = 'if?',
  ELSE = 'else',
  VAR = 'var',
  LET = 'let',
  CONST = 'const',
  FN = 'fn',
  TUP = 'tup',
  END = 'end',
  DEBUG = 'debug',
  INDEX = 'index',
  LENGTH = 'length',
  HAS = 'has',
  LISTSTART = '[',
  LISTEND = ']',
}

export const ENO_WORDS = Object.values(EnoWords)
